# Generated by Django 5.0.2 on 2024-02-13 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='seder_delete',
            new_name='sender_delete',
        ),
    ]
